# conda env create --file conda.yaml
name: mmwcas
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - cuda-nvcc=12.2.140
  - cmake=3.27.9
  - pip
  - pip:
    - "jax[cuda12]==0.4.35"
    - optax
    - jaxtyping
    - numba
    - open3d
    - pyparsing
    - pyhocon
    - tqdm
    - matplotlib
    - pathlib
    - pyyaml
    - opencv-python
    - scikit-image
    - pytransform3d
    - imageio
    - imageio-ffmpeg
    - rosbags
    - tyro