# conda env create --file conda.yaml
name: rpm
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - cuda-toolkit=12.2.1
  - cmake=3.27.9
  - open3d
  - numba
  - pip
  - pip:
    - "jax[cuda12]==0.5.0"
    - optax
    - jaxtyping
    - pyparsing
    - pyhocon
    - tqdm
    - matplotlib
    - pathlib
    - pyyaml
    - opencv-python
    - scikit-image
    - pytransform3d
    - imageio
    - imageio-ffmpeg
    - rosbags
    - tyro
    - point-cloud-utils
    - wandb
    - pandas
    - seaborn