program: run_map_sar.py

method: random

project: mm_map

entity: juite

metric:
  name: CD
  goal: minimize

parameters:
  map_extent:
    value: 10.0
  protect_range:
    value: 0.3
  resolution:
    value: 0.1
  azimuth_fov:
    values: [10.0, 20.0, 30.0, 40.0, 50.0, 60.0]
  bp_extra_fov:
    value: 10.0
  smooth_window:
    value: 1
  resolution_scale:
    value: 1
  amp_sigma:
    distribution: uniform
    min: 0.01
    max: 1
  ang_res:
    values: [0.25, 0.5, 0.75, 1.0]
  prob_hit:
    distribution: uniform
    min: 0.55
    max: 0.99
  prob_miss:
    distribution: uniform
    min: 0.2
    max: 0.49
  clamp_log_max:
    value: 3.5
  clamp_log_min:
    value: -2.0

command:
  - ${interpreter}
  - ${program}
  - ${args}
  - --en_wandb
  - --folder
  - /home/rpl/data/radar/cic
